language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gsl-bin
      - libgsl0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install md5sha1sum && brew install gsl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgsl0ldbl; fi

branches:
  only:
    - v1.1_dev

install:
  - source devtools/travis-ci/install_miniconda.sh
  - conda config --add channels omnia
  - conda config --add channels conda-forge # hightest priority

script:
  conda build --quiet devtools/conda-recipe

os:
  - linux

global:

  - PACKAGENAME="sstmap"

env:
  matrix:
    - python=2.7  CONDA_PY=27