language: c
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gsl

branches:
  only:
    - v1.1_dev


install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install gsl; fi
  - source devtools/travis-ci/install_miniconda.sh
  - conda config --add channels omnia
  - conda install numpy scipy matplotlib

script:
  conda build --quiet devtools/conda-recipe

os:
  - osx
  - linux

global:
  - PACKAGENAME="sstmap"

env:
  matrix:
    - python=2.7  CONDA_PY=27