language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install md5sha1sum && brew install gsl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -y libgsl0ldbl; fi

branches:
  only:
    - v1.1_dev

install:
  - source devtools/travis-ci/install_miniconda.sh

script:
  conda config --add channels omnia --add channels conda-forge

os:
  - osx
  - linux

global:

  - PACKAGENAME="sstmap"

env:
  matrix:
    - python=2.7  CONDA_PY=27