language: c
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gsl-bin
      - libgsl0-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum && brew install gsl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgsl0ldbl; fi

branches:
  only:
    - v1.1_dev

install:
  - source devtools/travis-ci/install_miniconda.sh
  - conda config --add channels omnia
  - conda config --add channels conda-forge # hightest priority

script:
  conda build --quiet devtools/conda-recipe

os:
#  - osx
  - linux

global:

  - PACKAGENAME="sstmap"
  - ORGNAME="solvationtools"

env:
  matrix:
    - python=2.7  CONDA_PY=27
#    - python=3.4  CONDA_PY=34
#    - python=3.5  CONDA_PY=35
#    - python=3.6  CONDA_PY=36

after_success:
  - source devtools/travis-ci/deploy_anaconda.sh