package:
  name: sstmap
  version: v1.0
source:
  path: ../../

build:
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - setuptools
    - gcc # [not win]

  run:
    - python 
    - libgcc # [linux and osx]
    - numpy
    - scipy
    - mdtraj
    - parmed
    - matplotlib

about:
  home: https://github.com/kamran-haider
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: Python tools for analysis of water molecules in MD trajectories.
