package:
  name: sstmap
  version: 1.1.0

source:
  path: ../../


requirements:
  build:
    - python
    - numpy 1.11.*
    - setuptools
    - gcc
    - toolchain
    - libgcc
    - gsl 22.0.0
    - libopenblas

  run:
    - python
    - libgcc
    - numpy
    - scipy
    - mdtraj
    - parmed
    - matplotlib
    - gsl 22.0.0
    - libopenblas

test:
  commands:
    - run_gist -h
    - run_hsa -h
  imports:
    - sstmap

about:
  home: https://github.com/KurtzmanLab/SSTMap
  license: MIT
  summary: Python tools for analysis of water molecules in MD trajectories.

